### ISSUE TITLE
`TOP_MODULE` make variable overwritten with multiple peripherals

### ISSUE THREAD

**Issue by P-Miranda** [IObundle/iob-uart#105]
## Description
- When multiple peripherals are present, each peripheral redefines the `TOP_MODULE` makefile variable.
- This variable is used to add source and header files for each peripheral
- In some cases this variable is also used to define targets to generate some of these header files

## Example
- For a system with `PERIPHERALS = UART TIMER`, we have in iob-soc's `hardware.mk`:
```make
(...)
#UART
include $(UART_DIR)/hardware/hardware.mk

#TIMER
include $(TIMER_DIR)/hardware/hardware.mk
(...)
```
- which gets expanded to:
```make
#UART
(...)
TOP_MODULE=iob_uart
(...)
#cpu accessible registers
$(TOP_MODULE)_swreg_def.vh $(TOP_MODULE)_swreg_gen.vh: $(UART_HW_DIR)/include/$(TOP_MODULE)_swreg.vh
	$(MKREGS) $< HW
(...)
#include files
VHDR+=$(wildcard $(UART_INC_DIR)/*.vh)
VHDR+=$(TOP_MODULE)_swreg_gen.vh $(TOP_MODULE)_swreg_def.vh
VHDR+=$(LIB_DIR)/hardware/include/iob_lib.vh
(...)
#TIMER
(...)
TOP_MODULE=iob_timer
#headers
VHDR+=$(wildcard $(TIMER_INC_DIR)/*.vh)
VHDR+=$(TOP_MODULE)_swreg_gen.vh $(TOP_MODULE)_swreg_def.vh
(...)
$(TOP_MODULE)_swreg_gen.vh $(TOP_MODULE)_swreg_def.vh: $(TIMER_INC_DIR)/$(TOP_MODULE)_swreg.vh
	$(LIB_DIR)/software/python/mkregs.py $< HW
```
- Notice that `TOP_MODULE` gets defined two times: one to `iob_uart` and another to `iob_timer`
- The variable `TOP_MODULE` is expanded to the last assigned value for the entirety of the makefile, leading to a wrong list of `VHDR` and respective targets
- In this case the `iob_uart`'s makefile fragment variables and targets are evaluated to wrong expressions leading to a wrong make recipe 
## Proposed solutions
1. Restrict usage of `TOP_MODULE` to makefile framents that are only evaluated in the context of the core.
  1.1. Keep using `TOP_MODULE` for targets like core documentation or simulation
  1.2. Do not use `TOP_MODULE` in the core's `hardware.mk`, `embedded.mk`, `software.mk`, `pc.mk`, `config.mk` fragments, since these are included by the iob-soc platform. Use the actual `TOP_MODULE` value in these cases.
2. Rename `TOP_MODULE` variables to `[CORE]_TOP_MODULE` to avoid variable collision between peripherals in the system

**Comment by jjts** [comment]
why not put TOP_MODULE?=something 

first called makefile is the first to set this variable
